# Generated by lynx_factory — the make + ./run contract for galeriaomaso.
#
#   make          install dependencies (idempotent — safe on every clone)
#   make run      start the project with its defaults (same as ./run)
#   make check    verify the toolchain this project needs is present

.DEFAULT_GOAL := all
.PHONY: all deps run check

all: deps

deps:  # verify the preview server (and build the site first if needed)
	@RUN_MODE=deps ./run

run: deps
	@./run

check:
	@RUN_MODE=check ./run
